USE [master]
GO
/****** Object:  Database [MERCEARIA]    Script Date: 20/10/2023 08:44:31 ******/
CREATE DATABASE [MERCEARIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MERCEARIA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\MERCEARIA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MERCEARIA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\MERCEARIA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MERCEARIA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MERCEARIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MERCEARIA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MERCEARIA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MERCEARIA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MERCEARIA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MERCEARIA] SET ARITHABORT OFF 
GO
ALTER DATABASE [MERCEARIA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MERCEARIA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MERCEARIA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MERCEARIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MERCEARIA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MERCEARIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MERCEARIA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MERCEARIA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MERCEARIA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MERCEARIA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MERCEARIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MERCEARIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MERCEARIA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MERCEARIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MERCEARIA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MERCEARIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MERCEARIA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MERCEARIA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MERCEARIA] SET  MULTI_USER 
GO
ALTER DATABASE [MERCEARIA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MERCEARIA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MERCEARIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MERCEARIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MERCEARIA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MERCEARIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MERCEARIA] SET QUERY_STORE = OFF
GO
USE [MERCEARIA]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 20/10/2023 08:44:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](150) NULL,
	[Fone] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUTO]    Script Date: 20/10/2023 08:44:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUTO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](150) NULL,
	[Preço] [float] NULL,
	[Estoque] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 20/10/2023 08:44:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](150) NULL,
	[NomeUsuario] [varchar](100) NULL,
	[Senha] [varchar](50) NULL,
	[Ativo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [MERCEARIA] SET  READ_WRITE 
GO
